### ISSUE TITLE
build auto encoder on my own images 

### ISSUE THREAD

**Issue by ProjectsRebository** [thierrydumas/autoencoder_based_image_compression#1]
i need help please i want to build auto encoder on my own images what should i do ?

**Comment by thierrydumas** [comment]
To build an auto-encoder on your own images, four modifications are needed.

(i) In the file "training_eae_imagenet.py", from line 99 to line 112, the training images and validation images are loaded. You simply need to create a file ".npy" at "datasets/imagenet/results/training_data.npy" storing a Numpy array containing your training images and create another file ".npy" at "datasets/imagenet/results/validation_data.npy" storing a Numpy array containing your validation images. For each of these two Numpy arrays, the array shape must be (`number_of_images`, `height`, `width`, `number_of_image_channels`). The data-type of each of these two Numpy arrays must be `numpy.uint8`.

(ii) In the file "eae/graph/EntropyAutoencoder.py", at line 133, the number of channels of the convolutional kernels of the first layer of the autoencoder is equal to 1. It should be equal to the number of channels in your images. For instance, for RGB images, it should be set to 3. Similarly, at line 221, the number of the convolutional kernels in the last layer of the autoencoder is equal to 1. It should also the equal to the number of channels in your images.

(iii) In the file "eae/graph/EntropyAutoencoder.py", at line 249, in the placeholder storing the input to the autoencoder in the Tensorflow graph, the 4th dimension, which is the number of channels, is equal to 1. It should be equal to the number of channels in your images.

(iv) In the file "eae/graph/EntropyAutoencoder.py", from line 696 to line 722, the method `checking_p_2` enables to visualize the convolutional kernels in the first layer and in the last layer of the autoencoder when the number of channels in the input to the autoencoder is equal to 1. You should re-code this method to visualize the same convolutional kernels in the case where the number of channels in the input to the autoencoder is different from 1. If you do not want to re-code it, comment line 243 to 248 in the file "training_eae_imagenet.py" to avoid calling this method.

After performing these modifications, you can run "training_eae_imagenet.py" as described in the documentation.
