### ISSUE TITLE
Question about calculating entropy

### ISSUE THREAD

**Issue by JingleiSHI** [thierrydumas/autoencoder_based_image_compression#2]
Hi Thierry,
Thank you very much for your excellent work. Now I am trying to use parts of your code to calculate entropy. However, there are several points that are not very clear for me, could you please give me some explanation?
1. To initialize the variable 'parameters', you used the function 'tile_cauchy', which means you suppose all samples follow Cauchy distribution, but in your paper, all samples follow Laplace distribution, is that because the two distributions are similar?
2. What is the range of your samples, are all samples within range [-1,1] or other range?
3. In the function 'index_linear_piece', [line 436](https://github.com/thierrydumas/autoencoder_based_image_compression/blob/d99a69b62f8d1e00441c8593aa9d54ac9d4c7e05/kodak_tensorflow/tfutils/tfutils.py#L436), why did you conduct the operation: nb_points_per_interval*samples ?

Thank you for your attention and your patience.

**Comment by thierrydumas** [comment]
Hi Jinlei,

1. In the paper, for each feature map in the stack of feature maps returned by the encoder, the density is comparable to the density of a Laplace distribution. This is valid after the training of the encoder exclusively.
The Cauchy distribution used to initialize `parameters` could have been replaced by a Gaussian distribution for instance. But, as you insinuate, weird distributions that are not likely to represent the distribution of one of these feature maps should not be used to initialize `parameters`, e.g. the continuous uniform distribution of support [0, 1000].
2. What do you mean saying "samples"? Are they the coefficients of a feature map in the stack of feature maps returned by the encoder? If so, the range is unknown. Each piecewise linear function used to approximate the density of a different feature map has an adaptive range, which is expanded if needed during the training phase.
3. This is explained by Equation (1) in the document "supplementary_material_0.pdf".

You're welcome.
