### ISSUE TITLE
The JPEG2000 file dumped cannot be opened again by Glymur

### ISSUE THREAD

**Issue by avinabsaha** [thierrydumas/autoencoder_based_image_compression#3]
Hi @thierrydumas ,

Can you specify versions of your dependencies. 

We are not able to read back the generated JP2 file using Glymur, it throws an error  that it is not a valid JP2 file.

**Comment by thierrydumas** [comment]
Dear Avinab,

The used version of Glymur for the tests is 0.8.10. Moreover, several dependencies have been added to "README.md".
